import tkinter
screen=tkinter.Tk()
screen.geometry("600x400") 
screen.configure(background="white")
screen.title("Calendar")
label=tkinter.Label(screen, text= "Calendar", font= ("arial", 40))
label.pack()
entry=tkinter.Entry(screen, text="Enter Year")
entry.pack()
button= tkinter.Button(screen, text= "Show Calendar")
button.pack()
exit_button= tkinter.Button (screen, text= "Exit")
exit_button.pack()
screen.mainloop()
